spring:
#   redis:
#     host: 172.17.0.1
#     #assword: 123456
#     port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/dc?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    hikari:
      initialization-fail-fast: true
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 600000
     connection-test-query: SELECT 1
     connection-init-sql: SELECT 1
  application:
    name: springcloud-provider-config
  profiles:
    active: test
logging:
  level:
    root: info
    org.hibernate : info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.yasaka.stock : debug
server:
  port: 8100